name:                 z-lab1-z-lib
version:              0.1.0.0
package-name:         lab1
lib-name:             lib
id:                   lab1-0.1.0.0-inplace-lib
key:                  lab1-0.1.0.0-inplace-lib
license:              BSD-2-Clause
maintainer:           danil228aeedj@mail.ru
author:               danil
category:             Math
abi:                  inplace
exposed-modules:      Euler
import-dirs:
    C:\Users\danil_emelin1\haskell-first-lab\app\lab1\dist-newstyle\build\x86_64-windows\ghc-9.4.8\lab1-0.1.0.0\l\lib\build\lib

library-dirs:
    C:\Users\danil_emelin1\haskell-first-lab\app\lab1\dist-newstyle\build\x86_64-windows\ghc-9.4.8\lab1-0.1.0.0\l\lib\build\lib
    C:\ghcup\msys64\mingw64\lib

library-dirs-static:
    C:\Users\danil_emelin1\haskell-first-lab\app\lab1\dist-newstyle\build\x86_64-windows\ghc-9.4.8\lab1-0.1.0.0\l\lib\build\lib
    C:\ghcup\msys64\mingw64\lib

dynamic-library-dirs:
    C:\Users\danil_emelin1\haskell-first-lab\app\lab1\dist-newstyle\build\x86_64-windows\ghc-9.4.8\lab1-0.1.0.0\l\lib\build\lib
    C:\ghcup\msys64\mingw64\lib

data-dir:             C:\Users\danil_emelin1\haskell-first-lab\app\lab1\.
hs-libraries:         HSlab1-0.1.0.0-inplace-lib
include-dirs:         C:\ghcup\msys64\mingw64\include
depends:              base-4.17.2.1
haddock-interfaces:
    C:\Users\danil_emelin1\haskell-first-lab\app\lab1\dist-newstyle\build\x86_64-windows\ghc-9.4.8\lab1-0.1.0.0\l\lib\doc\html\lab1\lab1.haddock

haddock-html:
    C:\Users\danil_emelin1\haskell-first-lab\app\lab1\dist-newstyle\build\x86_64-windows\ghc-9.4.8\lab1-0.1.0.0\l\lib\doc\html\lab1
